---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: test-dev

- name: test
  pull: never
  image: test-dev
  settings:
    repo: test-dev
    run: docker --version

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: test-dev
    repo: spritsail/docker-test
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: 742ca42edc2ecdac055c714c7d1719e6da90fb5b5b9defc9909aa10624621070

...
